In [2]:
import numpy as np

Q1

In [6]:
arr = np.array([1,2,3,6,4,5])
arr = arr[::-1]
arr

array([5, 4, 6, 3, 2, 1])

Q2

In [7]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[1,2], [3,4]])
arr1 == arr2

array([[ True,  True],
       [ True,  True]])

Q3

In [11]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
valX,countX = np.unique(x,return_counts=True)
mostFreqX = valX[np.argmax(countX)]
indicesX = np.where(x == mostFreqX)[0]
print(indicesX)
print(mostFreqX, end = '\n\n')

y = np.array([1,1,1,2,3,4,2,4,3,3,])
valY,countY = np.unique(y,return_counts=True)
mostFreqY = valY[np.argmax(countY)]
indicesY = np.where(y == mostFreqY)[0]
print(indicesY)
print(mostFreqY, end = '\n  ')


[0 5 7 8 9]
1

[0 1 2]
1
  

Q4

In [10]:
gfg = np.array([[4,1,9], [12, 3, 1], [4, 5, 6]])

print('Sum of all elements: ', gfg.sum())
print('Sum of elements row wise: ', gfg.sum(axis=1))
print('Sum of elements column wise: ', gfg.sum(axis=0))

Sum of all elements:  45
Sum of elements row wise:  [14 16 15]
Sum of elements column wise:  [20  9 16]
